### ISSUE TITLE
Creating SharedPreference object(instance) more than once

### ISSUE THREAD

**Issue by aryan-bilva** [suragch/minimalist_state_management_timer_app#1]
Hi, you have created shared preference instance two times in two overridden methods in shared_preferences_storage.dart file. Instead of that how would it be, if we create only one time outside the overridden methods.?

Please share your comments on this.

Summary :

Below code used two time in getTimeLeft() and saveTimeLeft(int seconds) in 
shared_preferences_storage.dart file

code :
final prefs = await SharedPreferences.getInstance();

**Comment by suragch** [comment]
Good question. In this case it's OK, though, because `SharedPreferences.getInstance()` returns a singleton. So no matter how many times we call `getInstance()`, we will always get the same instance.

**Comment by aryan-bilva** [comment]
Ok. Thank you.
